{"uuid":"5846d14a-d4e0-4817-9745-832dccde799c","historyId":"b99540ace0d77e3fb356d761a59ccb9f","fullName":"tests.WebAPP.Authentication_Tests.test_3","labels":[{"name":"package","value":"tests.WebAPP.Authentication_Tests"},{"name":"testClass","value":"tests.WebAPP.Authentication_Tests"},{"name":"testMethod","value":"test_3"},{"name":"parentSuite","value":"automationexercise.com WEB - Lukasz Radzajewski"},{"name":"suite","value":"Automated tests for WEB client"},{"name":"subSuite","value":"tests.WebAPP.Authentication_Tests"},{"name":"host","value":"DESKTOP-OTF0L9T"},{"name":"thread","value":"1312@DESKTOP-OTF0L9T.TestNG-test-Automated tests for WEB client-1(44)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Lukasz Radzajewski"},{"name":"story","value":"NEGATIVE FLOW"},{"name":"epic","value":"Web App Tests"},{"name":"feature","value":"LOGIN TESTS"},{"name":"severity","value":"normal"}],"links":[{"name":"TAP-0003","type":"issue"},{"name":"STORY-111","type":"tms"}],"name":"[US-111]/[3] I can't log into automationexercise.com using email \"lucastest1337@gmail.com\" & password \"wrongpass\"","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Ups, something went really bad! Even Michael Scofield couldn't have predicted that error! :) expected [http://automationexercise.com/] but found [https://automationexercise.com/]","trace":"java.lang.AssertionError: Ups, something went really bad! Even Michael Scofield couldn't have predicted that error! :) expected [http://automationexercise.com/] but found [https://automationexercise.com/]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat main.steps.MainPageSteps.iOpenHomePage(MainPageSteps.java:35)\r\n\tat tests.WebAPP.Authentication_Tests.test_3(Authentication_Tests.java:96)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\r\n\tat org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n"},"stage":"finished","description":"[US-111]/[2] As a user I can't log into automationexercise.com using email \"lucastest1337@gmail.com\" & password \"wrongpass\"","steps":[],"attachments":[],"parameters":[],"start":1714560535042,"stop":1714560541197}